version = 1
exclude_patterns = ["node_modules", "bower_components", "out", "bin", "build", "dist"]
test_patterns = ["**/__tests__/**", "**/*.spec.ts", "**/*.spec.js", "**/*.test.ts", "**/*.test.js"]

[[analyzers]]
  name = "javascript"
  enabled = true
  
  [analyzers.meta]
  plugins = ["react"]
  environment = ["vitest"]
